default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
google-plus: styles/gplus-theme-for-mastodon.scss
google-plus-dev: styles/gplus-theme-for-mastodon-dev.scss
dark-google-plus-dev: styles/dark-gplus-theme-for-mastodon-dev.scss
